# Nginx for Virtual-Vehicles Dockerfile

# http://stackoverflow.com/a/23328458/580268
# May need to run ln -sf /proc/self/fd /dev/ to get logs working?

FROM nginx

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>

ENV REFRESHED_AT 2015-07-05

COPY default.conf /etc/nginx/conf.d/default.conf	