# ELK stack for Virtual-Vehicles Dockerfile

FROM willdurand/elk

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>

ENV REFRESHED_AT 2015-07-08

COPY logstash-logspout-log4j2.conf /etc/logstash/logstash-logspout-log4j2.conf