# ELK stack for Virtual-Vehicles Dockerfile

FROM willdurand/elk

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>

ENV REFRESHED_AT 2015-07-08

COPY logstash-syslog.conf /etc/logstash/logstash-syslog.conf