# ELK stack for Virtual-Vehicles Dockerfile

FROM willdurand/elk

MAINTAINER Gary A. Stafford <garystafford@rochester.rr.com>

ENV REFRESHED_AT 2015-07-08

COPY logstash-logspout.conf /etc/logstash/logstash-logspout.conf
COPY multiline-logspout.conf /etc/logstash/multiline-logspout.conf